amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "differential"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.1
    update_min_d: 0.15
    z_hit: 0.95
    z_max: 0.05
    z_rand: 0.05
    z_short: 0.1
    set_initial_pose: True
    initial_pose:
      x: -1.0
      y: -3.0
      z: 0.0
      yaw: 0.0

amcl_map_client:
  ros__parameters:
    use_sim_time: True

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: True

bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_link
    bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    
bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: True

controller_server:
  ros__parameters:
    use_sim_time: True
    debug_trajectory_details: True
    min_vel_x: 0.0
    min_vel_y: 0.0
    max_vel_x: 0.26
    max_vel_y: 0.0
    max_vel_theta: 1.0
    min_speed_xy: 0.0
    max_speed_xy: 0.26
    min_speed_theta: 0.0
    min_x_velocity_threshold: 0.001
    # Add high threshold velocity for turtlebot 3 issue.
    # https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/75
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    acc_lim_x: 2.5
    acc_lim_y: 0.0
    acc_lim_theta: 3.2
    decel_lim_x: -2.5
    decel_lim_y: 0.0
    decel_lim_theta: -3.2
    vx_samples: 40
    vy_samples: 0
    vtheta_samples: 80
    sim_time: 2.9
    linear_granularity: 0.1
    angular_granularity: 0.025
    xy_goal_tolerance: 0.25
    transform_tolerance: 0.2
    short_circuit_trajectory_evaluation: True
    stateful: True
    critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
    BaseObstacle.scale: 0.01     #0.25 Approach
    BaseObstacle.sum_scores: True
    PathAlign.scale: 41.0
    GoalAlign.scale: 18.0
    PathDist.scale: 41.0
    GoalDist.scale: 18.0
    RotateToGoal.scale: 32.0
    

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 5.0
      robot_base_frame: base_link
      use_sim_time: True
      #global_frame: odom
      robot_radius: 0.22
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      plugin_names: [
        "obstacle_layer",
        "voxel_layer",
        "people_filter_layer",
        "inflation_layer",
        "social_layer",]
      plugin_types: [
        "nav2_costmap_2d::ObstacleLayer",
        "nav2_costmap_2d::VoxelLayer",
        "social_navigation_plugins/PeopleFilterLayer",
        "nav2_costmap_2d::InflationLayer",
        "social_navigation_plugins/SocialLayer",]
      robot_radius: 0.22
      inflation_layer:
        cost_scaling_factor: 3.0
      obstacle_layer:
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          raytrace_range: 3.0
          inf_is_valid: True
          clearing: True
          marking: True
          data_type: "LaserScan"
      voxel_layer:
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: pointcloud
        pointcloud:
          topic: /intel_realsense_r200_depth/points
          max_obstacle_height: 2.0
          raytrace_range: 4.0
          inf_is_valid: True
          clearing: False
          marking: False
          data_type: "PointCloud2"
      static_layer:
        map_subscribe_transient_local: True
      people_filter_layer:
        enabled: True
        tf_prefix: "agent_"
        filter_radius: 0.45
      social_layer:
        enabled: True
        debug_only: False
        tf_prefix: "agent_"
        intimate_z_radius: 0.45
        personal_z_radius: 1.2  # Must be lower than half width and half height
        use_proxemics: True
        orientation_info: True
        action_names: ["following", "escorting", "approaching", "default"]
        escorting:
          var_h: 1.0
          var_s: 1.0
          var_r: 1.0
          n_activity_zones: 2
          activity_zone_phi: 1.5707
        following:
          var_h: 1.0
          var_s: 1.0
          var_r: 0.7
          n_activity_zones: 1
          activity_zone_alpha: 0.7853
          activity_zone_phi: 3.1415
        approaching:
          var_h: 0.8
          var_s: 1.0
          var_r: 1.0
          n_activity_zones: 1
          activity_zone_alpha: 0.7853
          activity_zone_phi: 0.0

      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: True
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 5.0
      robot_base_frame: base_link
      global_frame: map
      use_sim_time: True
      plugin_names: [
        "static_layer",
        "obstacle_layer",
        "voxel_layer",
        "people_filter_layer",
        "inflation_layer",
        "social_layer"]
      plugin_types: [
        "nav2_costmap_2d::StaticLayer",
        "nav2_costmap_2d::ObstacleLayer",
        "nav2_costmap_2d::VoxelLayer",
        "social_navigation_plugins/PeopleFilterLayer",
        "nav2_costmap_2d::InflationLayer",
        "social_navigation_plugins/SocialLayer"]
      robot_radius: 0.22
      resolution: 0.1
      obstacle_layer:
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          raytrace_range: 6.0
          inf_is_valid: True
          clearing: True
          marking: True
          data_type: "LaserScan"
      voxel_layer:
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.1
        z_voxels: 8
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: pointcloud
        pointcloud:
          topic: /intel_realsense_r200_depth/points
          max_obstacle_height: 2.0
          raytrace_range: 4.0
          inf_is_valid: True
          clearing: False
          marking: False
          data_type: "PointCloud2"
      static_layer:
        map_subscribe_transient_local: True
      people_filter_layer:
        enabled: True
        tf_prefix: "agent_"
        filter_radius: 0.45
      social_layer:
        enabled: True
        debug_only: False
        tf_prefix: "agent_"
        intimate_z_radius: 0.45
        personal_z_radius: 1.2
        use_proxemics: True
        orientation_info: True
        action_names: ["following", "escorting", "approaching", "default"]
        escorting:
          var_h: 1.0
          var_s: 1.0
          var_r: 1.0
          n_activity_zones: 2
          activity_zone_phi: 1.5707
        following:
          var_h: 1.0
          var_s: 1.0
          var_r: 0.7
          n_activity_zones: 1
          activity_zone_alpha: 0.7853
          activity_zone_phi: 3.1415
        approaching:
          var_h: 0.8
          var_s: 1.0
          var_r: 1.0
          n_activity_zones: 1
          activity_zone_alpha: 0.7853
          activity_zone_phi: 0.0
      
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: True
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "turtlebot3_world.yaml"

planner_server:
  ros__parameters:
    use_sim_time: True
    tolerance: 2.7
    use_astar: false
    allow_unknown: false

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    plugin_names: ["wait"]
    plugin_types: ["nav2_recoveries/Wait"]
    global_frame: odom
    robot_base_frame: base_link
    transform_timeout: 0.1
    use_sim_time: true
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

robot_state_publisher:
  ros__parameters:
    use_sim_time: True
    
